### ISSUE TITLE
Installation Instructions on Linux Mint/Ubuntu

### ISSUE THREAD

**Issue by Sixty4ce** [ther0n/beefweb_mpris#12]
Hey there!

I'm trying to get this working on Linux Mint 21.3 Cinnamon, and I'm having a bit of trouble.

I'm pretty new to working with Python like this, so I don't quite know what I'm doing wrong lol. I've tried to install the required dependencies with Synaptic, but I don't know if I'm missing one, or if this is an issue with something else. I've tried to search online about this issue, but I haven't been able to find anything helpful thus far, or at least what I've found goes a bit over my head.

I've provided the terminal output in this here txt file in the hopes that someone smarter than me could make heads or tails of it.
[output.txt](https://github.com/user-attachments/files/16914446/output.txt)

Thanks in advance!

**Comment by ther0n** [comment]
I need to update my installation instructions again since I found that the best way to install isn't with `pip` but with `pipx`

Try running `sudo apt install pipx git libcairo2-dev python3-dev libgirepository1.0-dev` and then install with `pipx install git+https://github.com/ther0n/beefweb_mpris.git`

Run `pipx ensurepath` and restart your shell/terminal to make sure ~/.local/bin is in your path. Create a file at `~/.local/bin/foobar2000` that launches foobar2000 with wine (make sure it has `#!/bin/sh` at the top!) for example:
```sh
#!/bin/sh
env WINEPREFIX="/home/theron/.wine" wine "/home/theron/.wine/drive_c/Program Files/foobar2000/foobar2000.exe"
```

Edit `~/.config/beefweb_mpris/config.yaml` to launch `~/.local/bin/foobar2000` and edit the username and password if configured.

**Comment by Sixty4ce** [comment]
Hey, this worked a treat! Thanks a bunch! ^^
